### ISSUE TITLE
(Mac users) Upgrading MAMP 

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-spring2018#12]
MAMP released an update yesterday - it's now at version 4.4.

For us, the most relevant part of this update is it now includes **PHP v7.2.1** (previously 7.1.12).

~~We don't need the upgraded version of PHP right now, but we will come Week 5 when we move into using Laravel which, as of it's the latest release, requires PHP >=7.1.3.~~

*Edit: At first glance I read the version numbers as decimals and interpreted 7.1.12 as < 7.1.3, but that's not true! 7.1.12 is > 7.1.3 ([hat-tip @jaechong for spotting this](https://github.com/susanBuck/dwa15-spring2018/issues/38#issuecomment-368963982)). So the version of MAMP we started with *does* technically meet the Laravel specs. However, the older PHP versions will cause some dependency discrepancies between our local and prod servers, so I still recommend doing these updates.*

__For the MAMP students out there - you can update now or wait until Week 5 - it's up to you. There's no harm in upgrading now.__

## To update
1. Make a copy of `/Applications/MAMP/conf/apache/extra/httpd-vhosts.conf` which contains any VirtualHosts blocks you've made so far this semester.
2. Close MAMP
3. Re-download the latest release of MAMP here: <https://www.mamp.info/en/downloads>
4. Initiate the installer from the download. The installer will copy over your existing `htdocs` folder into the new install.
5. When the installer is complete, replace the new `/Applications/MAMP/conf/apache/extra/httpd-vhosts.conf` file with the copy you made in step 1.
6. Open `/Applications/MAMP/bin/php/php7.2.1/conf/php.ini` and configure your error reporting settings [as described in this note set](https://github.com/susanBuck/dwa15-spring2018/blob/master/php/error-reporting-and-configs.md) (The notes still refer to v7.1.12 - but remember now you're working in 7.2.1 so you should be editing that config file)
7. Open `/Applications/MAMP/conf/apache/httpd.conf` and uncomment the line `Include /Applications/MAMP/conf/apache/extra/httpd-vhosts.conf` so your local domains will still work ([ref](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/local-domain.md#step-1-tell-apache-to-use-the-virtual-hosts-file))

Note: In this new version of MAMP, the preferences button was removed from the main window. You now access it from the menu bar (*MAMP* > *Preferences*)

## Windows/XAMPP users 
No action is necessary as the version of XAMPP you're using should already be using PHP 7.2.1

## DigitalOcean Droplets
The version of PHP on our DigitalOcean droplets will also need to be updated come Week 5, but I'll publish the relevant notes for that when the time comes.

**Comment by hsappa** [comment]
Just upgraded and it wasn't without hiccup.  Some of the web server configurations didn't transfer over.

To save time for those who want to get back up and running quickly: go into Preferences and set the ports for 80 (Apache) and 3306 (MySQL).

Also, the following files will need to be updated per the [Week 2 notes](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/local-domain.md):

- MAMP/conf/apache/httpd.conf
- MAMP/conf/apache/extra/httpd-vhosts.conf

The upgrade preserved the previous MAMP install and it was possible to copy the relevant changes from the previous http-vhosts.conf.

**Comment by susanBuck** [comment]
Thanks for the additional tips, @hsappa!

**Comment by voggi** [comment]
The above upgrade will also reset the **php.ini** file so that errors are no longer displayed. 

If you set your error reporting as shown in [Quiz 2](https://github.com/susanBuck/dwa15-spring2018/blob/master/php/error-reporting-and-configs.md), make sure you do this in the **php7.2.1** folder and not the **php7.1.12**.

It took me a few minutes to see that.

**Comment by susanBuck** [comment]
Good catch, @voggi. I updated my original instructions to reflect both yours and @hsappa's note.
