### ISSUE TITLE
reformat code shortcut

### ISSUE THREAD

**Issue by amushal** [susanBuck/dwa15-spring2018#14]
FYI, the **reformat code** shortcut on my PhpStorm 2017.3.4 Build #PS-173.4548.32 is:
 
* command + option + L

**Comment by mcm223** [comment]
I have to say, I'm really impressed with PhpStorm's formatting options. I took CSCI E-65g last semester which uses Xcode with Swift, and the formatting functionality there is really basic. I'm going to get spoiled with all these options in PhpStorm!
