### ISSUE TITLE
The PHPStorm warning about the ?? operator in the lecture 

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/dwa15-spring2018#15]
All,

I didn't see this posted in another issue, but during the second to last lecture PhpStorm "warned" that the coalescing operator was only allowed in PHP v7. I found this page to address the issue (setting PhpStorm to default to a different PHP code base):

https://www.jetbrains.com/help/phpstorm/2017.3/configuring-local-php-interpreters.html

Hope this helps,

Jerry

**Comment by johnpura** [comment]
Nice find!

**Comment by susanBuck** [comment]
Good tip, thanks for sharing Jerry.

Below is a summary of how to tell PhpStorm which install of PHP to use.

I suggest choosing the same PHP your local server is using, so in the screenshot mine is set to `/Applications/mamp/bin/php/php7.2.1/bin/php`

XAMPP users you'd want to set it to `C:\xampp\php\php.exe`

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/237711/36080460-6677cbb8-0f5e-11e8-8646-f2751e0cc020.png">
