### ISSUE TITLE
Using PhpStorm vs other IDE/Editors?

### ISSUE THREAD

**Issue by johnpura** [susanBuck/dwa15-spring2018#17]
Hi,

I have been using Visual Studio Code for my projects. It seems to be very intuitive and is also free.

I was wondering if there were many differences between the two tools and if PhpStorm is needed to develop our projects later in the class?

**Comment by susanBuck** [comment]
There's nothing in PhpStorm that is a "must" for work in this course. My main requirement is just that code be properly formatted - whether you do it manually yourself, or with the assistance of a feature of your code editor (as I demo'd w/ PhpStorm).

Students are welcome to use other editors if it fits their needs. I can't speak to the differences between PhpStorm and Visual Studio Code, so any other students with experience wither either/both can chime in.

**Comment by bwilks26** [comment]
Hi @johnpura , in my experience, using PhpStorm, along with the other various products like WebStorm and IntelliJ from JetBrains is really helpful. The suite of products, including PhpStorm, has a variety of useful developer tools that can help in many different applications. For example, the massive extensions and plugins library that JetBrains provides can assist with things such as integrations, typescript-ting, and multi-language support. It is both a visually helpful tool along with a multi-level helpful development tool, including features like easy viewing on localhost, easy refactoring, and debugging features. There is a small learning curve when going into the interface itself first, but well worth it later on.

**Comment by johnpura** [comment]
Thanks all for you feedback...much appreciated!

**Comment by brianyingling** [comment]
@johnpura I'm partial to Visual Studio Code myself, so I'm finding myself also using it. VS Code extensions are extensive, terminal is built in, and has great git integration (though I always use the command line).
