### ISSUE TITLE
'cover_url' vs 'cover' in JSON

### ISSUE THREAD

**Issue by archerdave** [susanBuck/dwa15-spring2018#18]
In Week 3, Part 4 video, the video demonstrates accessing the image of the book cover by accessing the 'cover_url' key in the array.  However, the JSON (and thus our array) refers to that URL as 'cover'.  If it is left unchanged, it results in a "broken image" icon.  If corrected, the covers display as shown in the video.

**Comment by susanBuck** [comment]
The JSON I see is using `cover_url` : <https://github.com/susanBuck/dwa15-php/blob/master/books.json>
Can you confirm if this is the same version of books.json you're using? Or maybe I have a link somewhere in the notes to an older version of books.json?

**Comment by archerdave** [comment]
I copied the JSON from <http://php.dwa15.com/books.json>.

I'm wondering if I accidentally went to your "PHP in action" demo site..

**Comment by susanBuck** [comment]
Ah ok that explains it - I had not pulled recent changes to php.dwa15.com so it's got an outdated version up there. Just sync'd everything up. Thanks for drawing attention to this!
