### ISSUE TITLE
Getting Cmder to run inside PhpStorm on Windows 10

### ISSUE THREAD

**Issue by ElijahMR** [susanBuck/dwa15-spring2018#19]
Hello everyone,

I wanted to get Cmder to run inside PhpStorm instead of the standard CMD and while Googling I managed to find this issue thread on the Cmder Github: https://github.com/cmderdev/cmder/issues/282

What worked for me was the very last comment by LambdaExpression: https://github.com/cmderdev/cmder/issues/282#issuecomment-359697772

Take a look at the comment but here it is summarized:

1. Open up `<where you unzipped cmder to>\cmder-master\vendor\init.bat` in your preferred editor.
2. Add this code (with your directory replacing the <> tags) on line 3:
````batch
set CMDER_ROOT=<where you unzipped cmder>\cmder-master
set DL=%~d0
set LAST_CD=%cd%
````
My directory is `C:\Users\Elijah\Documents\Portable Installations\cmder-master` for example.

This code to line 192:
````batch
%DL%
cd %LAST_CD%
````
3. Open PhpStorm and then click on `File->Settings->Tools->Terminal`
4. Under Application Settings you should see a field named Shell Path. Enter this there:
````
"C:\Windows\System32\cmd.exe" /k "<where you unzipped cmder>\cmder-master\vendor\init.bat"
````
5. Click OK and then Click on Terminal. You should see this if you have the hello-world project open like I do:
![Cmder in PhpStorm](http://img.mystphy.sx/ss%20%282018-02-12%20at%2012.08.23%29.png)

**Comment by susanBuck** [comment]
Fantastic tip! Thank you for sharing.

**Comment by gaderrick** [comment]
Nice! I found a similar thread att [intellij's]<https://intellij-support.jetbrains.com/hc/en-us/community/posts/207262689-Any-way-to-use-Cmder-terminal-in-PHPstorm> website.

**Comment by Caroga** [comment]
could you share a gist of the `init.bat` to see the final result? 
As line 3 and line 192 are comments in my version.

**Comment by ElijahMR** [comment]
Sure here you go: https://gist.github.com/ElijahMR/703a8c1d43b5876c8a0cae9714fcca72

**Comment by Caroga** [comment]
Thank you very much!
