### ISSUE TITLE
PSR-2 coding style for variables/properties

### ISSUE THREAD

**Issue by johnpura** [susanBuck/dwa15-spring2018#20]
Hello, 

When writing PHP scripts that do not rely on a class (a script that does some basic processing), do we need to add the visibility modifiers when declaring variables and methods? If not, is that something that we would include in the Code style divergences of the the readme file?

...I interpreted some of the the PSR standards to apply to PHP OOP, but the general format of writing PHP code as universal to all php files.

Thanks!

**Comment by susanBuck** [comment]
Nope, visibility modifiers are not required outside of the context of a class.
