### ISSUE TITLE
Format of HTML?

### ISSUE THREAD

**Issue by archerdave** [susanBuck/dwa15-spring2018#21]
So, we have PSR-1 and PSR-2 for PHP, and that's a good thing.

However, a recent experience has pointed out to me that the rules for formatting PHP don't necessarily apply to pages written in HTML (I'm looking at you, Eclipse!).  This has led me to question of much of the PHP formatting rules in PSR-1 and PSR-2 should apply to pages that mixed HTML and PHP, such as our "display" pages (regardless of what editing environment we are in).

**Comment by susanBuck** [comment]
This is briefly touched upon here: [Code Style: PHP Code in display files](https://github.com/susanBuck/dwa15-spring2018/blob/master/misc/code-style.md#php-code-in-display-files): 

> You may diverge PSR-1/PSR-2 guidelines in display files (.html, .blade.php) that incorporate PHP if it's for the purposes of writing more legible display code.

From this, you can infer that for the *Code style divergences* section of your project README.md file, you do not have to list divergences used in your display files.

The PSR guidelines are specific to pure-php files, not display files where we're using PHP less as a programming language and more as a templating language.

Some examples - I often use inline control structures in display/HTML files:
```
<option value='mon' <?php if ($day == 'mon') echo 'selected'?>>Monday</option>
```
Also, it's not uncommon for lines in display files to have lines that exceed 80 characters in length. 

All that being said, you shouldn't completely ignore the guidelines in your display files - for example, there's no reason to switch your casing on keywords like `null`, `true`, `false`, or switch the indentation style, etc.

I'd poke around your settings in Eclipse and see if there's a way to configure it to not flag PHP formatting issues in files that contain HTML.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any questions are still pending.
