### ISSUE TITLE
code styling inconsistency

### ISSUE THREAD

**Issue by amushal** [susanBuck/dwa15-spring2018#23]
I am seeing inconsistency with auto *code styling* using **PHPStorm**.  I am using the dwa jar settings.  Here is an example (note how the **HTML** format is different on the ```input element```)

```html
                  <div class="input-group">
                            <input type="text"
                                   class="form-control"
                                   id="xxx"
                                   name="xxx"
                                   placeholder="xxx"
                                   value='<?= $form->prefill('xxx', '') ?>'>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="yyy">yyy</label>
                        <input type="number" class="form-control" placeholder="yyy" id="yyy" name="yyy"
                               value='<?= $form->prefill('yyy', '') ?>'>
                    </div>
```

**Comment by susanBuck** [comment]
Are you referring to the fact that the attributes for the first input are all on their own line, but in the second input they sit on the same line?

This is related to a setting under *Preferences :: Editor :: Code Style :: HTML :: Wrap Attributes*

The option I have mine set to is *Chop down if long*.

I believe the reason the second input is not getting "chopped down" is it's not longer than 120 chars.

To test, try manually putting all the attributes for the second input on the same line. This will force it to be > 120 characters and when you reformat the code, it should chop down the attributes.

**Comment by amushal** [comment]
Yes, I was referring to that.  I did as suggested on second input and it did chop it down like the first one now, thanks.  I am not used to seeing it in such format but I guess I should do this on all other "short ones" and let the code formatter chop down if necessary for consistency.
