### ISSUE TITLE
Form design flow - Ajax?

### ISSUE THREAD

**Issue by johnpura** [susanBuck/dwa15-spring2018#24]
I would like to use AJAX to pass data from my form to my PHP script and use the response to update the DOM with the results. Is this an acceptable flow design in Project 2? 

The flow of the AJAX request would be...

index.html  ->  ajaxRequest.js  ->  processRequest.php 

And the response is would be the reverse order, but updating the DOM with the data from the response.

**Comment by susanBuck** [comment]
Sure, that sounds fine to me. 

What kind of data will your server respond to the Ajax request with? 
Most common is to respond with something like JSON, which your JS then parses and injects into the HTML/DOM.

I caution against doing something like the following in your response: 
```
# PHP Logic code here to generate results...
return "<div class='results'>".$results."</div>";
```

With this, one is falling into the trap of display vs. logic mixing we want to avoid.
Not saying you were planning on doing this, just want to be clear. : )

**Comment by johnpura** [comment]
Yes, I plan on sending back the results of my PHP script as a JSON object, parsing it with JS, and manipulate the DOM. The reason for this is because I think it is best to separate client code from server-side code, so there would be no PHP tags in my views. I would use PHP only for processing my logic.

**Comment by susanBuck** [comment]
Sounds great.
