### ISSUE TITLE
Initialize the Numeric Values of a Function

### ISSUE THREAD

**Issue by oarangel** [susanBuck/dwa15-spring2018#25]
When I first load my P2 page, the following **Warning** is displayed:

_**Warning: A non numeric value  encountered in /Applications/MAMP/htdocs/P2/logic.php on line 39**_
_**Warning: A non numeric value  encountered in /Applications/MAMP/htdocs/P2/logic.php on line 39**_

The function is looking for initial values to perform the calculation. 
If I set initial function values, the form populates those initial values. 

I used the **_`if ($_GET)`_** before the function execution statement but the **Warning** still present when I first load the page.

Here is the variable declaration generating the function initial error: `$totalAmt= isset($_GET['totalAmt']) ? $_GET['totalAmt'] : ' ';` 

Again the **Warning** is only present when I first load the page, no _Errors_ are displayed after that initial load.

Any Comments, Suggestions?

**Comment by oarangel** [comment]
I tried an `if (!empty(_$GET)` statement before executing the function and the Warning went away.
Problem is that I need to use the `!empty` statement in two files (display and logic) because the display file uses the function output and no **Global** variables were declared

**Comment by susanBuck** [comment]
Please share your Github URL so classmates can see the full context of the problem you're describing.

**Comment by oarangel** [comment]
This is the Github URL [http://github.com/oarangel/P2](url)

**Comment by susanBuck** [comment]
I just cloned your project and did not see the same warning when running your application. 
Going to assume the issue referenced in this post has been resolved, so I'm going to close this thread, but I will take a look at your other threads to see if there are still pending issues.
