### ISSUE TITLE
Display P2 Project  in Local Server but Unable to run in the Production Domain

### ISSUE THREAD

**Issue by oarangel** [susanBuck/dwa15-spring2018#27]
I can run my project on the local server but I am not able to run the domain server page.
I used the Validator to check the local server page with no errors or warnings to report.
I can ping the domain server.
Any suggestions?

**Comment by oarangel** [comment]
The server apache2 error log shows the following error:

_**[Mon Feb 19 11:57:18.216486 2018] [:error] [pid 29844] [client 199.255.117.85:52530] PHP Parse error:  syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) in /var/www/html/p2/index.php on line 67**_

Fixed the end of file error, updated the Github project and Production Server files, the page now loads. 

The error above was mentioned in the videos but it is not clear to me why the local server version displays and not the  production server version.

**Comment by susanBuck** [comment]
Revisit the notes on [Error reporting & configs](https://github.com/susanBuck/dwa15-spring2018/blob/master/php/error-reporting-and-configs.md).

By default, our production servers are configured to suppress error messages from displaying on the screen. This is an ideal setting for a production server because we generally don't want visitors to see errors in their raw form.

Another tip - in future posts, classmates can more effectively help you troubleshoot problems if they can see your code.

From <https://dwa15.com/issues-forum>:

> Include relevant code snippets.
> 
> Include your Github URL to the relevant repository and make sure your code is up to date. We can most effectively help you when we can replicate the problem on our own system.

**Comment by oarangel** [comment]
The Error and Display features were ENABLED per the  Error reporting & configs but this may be considered a startup error? Currently turned off which will explain no errors reported?

> display_startup_errors| Off | Off-- | -- | --

**Comment by bwilks26** [comment]
Hi @oarangel , I had a similar problem when initializing my production environment. My files would not display on the production server, but they would validate and would show up on my development environment in MAMP. I had to do a hard reset of the production server and also did have trailing whitespace in my php file (found after a fair chunk of time debugging) from copying over my code at one point. Glad you were able to resolve your issue!

**Comment by susanBuck** [comment]
@oarangel When you say error and display settings were enabled, do you mean in your local config file or your production config file?

**Comment by oarangel** [comment]
Local config file **phpinfo**

**Comment by susanBuck** [comment]
Ok, I see - so errors *were* enabled locally, so if there was a syntax error you *should* have seen it.

Hm, can't really say for sure what was happening here. It's possible the config file had been changed but the server had not been restarted (something @bwilks26 alludes to)?

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
