### ISSUE TITLE
Enable/disable dropdown box on checkbox selection

### ISSUE THREAD

**Issue by anup24** [susanBuck/dwa15-spring2018#29]
Looking for some inputs on enabling/disabling dropdown on checkbox selection. I did google search however have not been able to find correct fix. My code and screenshot of the screen below for reference.

I am reading values from post form and my checkbox name is 'add_symbol_checkbox' and dropdown name is 'add_symbol'

`$_POST["add_symbol"]`

I tried this -> `$_POST["add_symbol"].attr("disabled", false)` however did not work. One option would be reading it using html document id but is there any solution apart from that?

<img width="415" alt="screen shot 2018-02-19 at 2 06 25 pm" src="https://user-images.githubusercontent.com/27923213/36393699-a30209ba-157e-11e8-8ccf-de1ba92ab80b.png">

Thanks.

**Comment by reelmatt** [comment]
Something you could try is using a PHP if-statement to assign a class to the dropdown select. For example

```html
<input type="checkbox" name='add_symbol'>Include a special character
<select <?php if($_POST['add_symbol']=='disabled') echo "class='HIDE'"; ?>>
    <option value="0">Select a symbol</option>
</select>
```

I tried to get the names/values/variables similar to your screenshot, but some tweaking will probably be necessary. And just create an entry in your CSS that's something like this

```css
.HIDE {
    display: none;
}
```

**Comment by mcm223** [comment]
In my opinion, I'd use JavaScript for this since the desired change can be done purely using client-side processing. For example, something like this would work:
```javascript
<script>
var checkbox = document.querySelector("input[name=add_symbol_checkbox]");
var dropdown = document.getElementById('dropdown'); // Add an id to your dropdown so this will grab it

// Listen for changes to the checkbox and toggle visibility on the dropdown
checkbox.addEventListener('change',function() {
	if(this.checked){
		dropdown.style.visibility = "visible";
	} else {
		dropdown.style.visibility = "hidden";
	}
});
</script>
```

**Comment by amushal** [comment]
Since this needs to be done before you submit to server, it should be via client side as [@msm223](https://github.com/mcm223) mentioned.  I would add an ```onclick()``` or ```onchange()``` trigger event to the checkbox and enable/disable the drop down:

**Something like this should do**:
```
<input type="checkbox" id="enable" onclick="document.getElementById('mySelect').disabled = !this.checked">
```

**Comment by anup24** [comment]
Thanks @reelmatt @mcm223 & @amushal for your inputs.

I just used simple javascript function to enable/disable dropdown using document id.

Thanks for the example @mcm223
