### ISSUE TITLE
small display area for results of search on dwa15.com

### ISSUE THREAD

**Issue by archerdave** [susanBuck/dwa15-spring2018#31]
I just used the "Search" feature on dwa15.com (<https://dwa15.com/search>) to look for "foobooks".  (I was looking for the changes to the foobooks code base between videos 3 and 4.)  The search returned four results, but it returned them in a rather small window-ish area of the page which requires scrolling to see all the results.  Additionally, the page background and results background are indistinguishable, so the need (and ability) to scroll wasn't readily apparent.

**Comment by susanBuck** [comment]
Thanks for the note @archerdave! That was annoying. Just fixed it.

(FYI - for future stuff like this, you can just shoot me an email directly; try to keep the Issues forum devoted to troubleshooting, projects, curriculum, etc.)
