### ISSUE TITLE
require('') vs require ''

### ISSUE THREAD

**Issue by archerdave** [susanBuck/dwa15-spring2018#32]
I've noticed that some files (such as *index-logix.php*) use ```require('Books.php'); ``` while others (such as *all.php*) use ```require 'helpers.php';```.  Is there a difference between the two?

**Comment by mcm223** [comment]
I think you can write it either way; the documentation does not specify: [http://php.net/manual/en/function.require.php](http://php.net/manual/en/function.require.php).

However, the first user comment in that documentation does (albeit jokingly) point out that using parenthesis can lead to it being mistaken for a function.

**Comment by susanBuck** [comment]
As @mcm223 noted, you can write it either way, but without parenthesis is the most appropriate.

Out of old/bad habit, I sometimes still use the parenthesis, as you've spotted. I'll clean up those examples.
