### ISSUE TITLE
Digital Ocean Droplet Reboot (Spectre/Meltdown)

### ISSUE THREAD

**Issue by mcm223** [susanBuck/dwa15-spring2018#34]
Hi -- I just got a notification from Digital Ocean notifying me that my droplet will be offline temporarily as they work on their fleet for security patches related to Spectre and Meltdown. Since Assignment 2 is presumably being graded right now, I wanted to give a heads up that this may impact some of our assignment availability.

According to Digital Ocean, mine will be offline from 10:00-11:00 EST on Monday the 26th.

**Comment by smaaliki** [comment]
I only got a notification that new droplets cannot be created, but older ones will not be affected.  Also my notification was for Mar 1.

**Comment by susanBuck** [comment]
Noted. 👍
