### ISSUE TITLE
P2 Share thread

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-spring2018#37]
It can be interesting/useful to see the work your classmates are creating. 

Given this, I encourage you to reply to this thread with the **Github URL to your project 2** (no need to include the production URL - we should be able to find it via your README.md file).

(Participating in this thread is **optional** and will not impact your grade on the project.)

**Comment by mcm223** [comment]
Here is mine: https://github.com/mcm223/p2

It's fairly similar to the Foobooks example, but tweaked slightly. The functionality was inspired by a Valentine's Day promotion at a book store in Belmont, MA that my friend works at.

**Comment by brianyingling** [comment]
I did the Pig Latin translator: https://github.com/brianyingling/p2

Enjoy!

**Comment by amushal** [comment]
I did a product cost calculator based on **No of Payments, Shipping/Tax (if any), with discount factor of percent and/or Dollar amount:** https://github.com/amushal/p2

**Comment by ElijahMR** [comment]
https://github.com/ElijahMR/p2

I ended up doing a simple age calculator for various time scales. It will also tell you the number of leap years that have passed since the date you input.

**Comment by johnpura** [comment]
I wrote a simple car loan calculator that determines how much of a loan you can afford based on your monthly payments. When I was shopping for a car a year ago, I noticed that the online calculators did the reverse. It calculated your monthly payments based on the amount of the loan. I thought it would be better to know how much you can borrow based on you monthly budget.   

https://github.com/johnpura/p2.git

**Comment by JoelTurnblade** [comment]
I wrote a mental arithmetic practice app.  You input the operation (add, subtract, multiply, int divide) and the number of input digits.  The app generates two random numbers with the correct number of digits and will tell you if you performed the mental calculation correctly.

https://github.com/JoelTurnblade/p2

**Comment by tanyaflint** [comment]
I did a simple Bill Splitter

https://github.com/tanyaflint/p2

**Comment by mildredfakoya** [comment]
I did a client code generation app.
[](https://github.com/mildredfakoya/p2)

**Comment by gaderrick** [comment]
Here's a Scrabble scoring app with a dictionary lookup option: https://github.com/gaderrick/p2

**Comment by mcm223** [comment]
@gaderrick - The scrabble tiles that spell out the word are really cool!

**Comment by voggi** [comment]
Hi everyone - I also implemented the [bill splitter](https://github.com/voggi/p2).

**Comment by bwilks26** [comment]
https://github.com/bwilks26/p2

I did a Bill Splitter implementation as seen in the examples in Project 2. It includes custom styling and a custom layout while implementing Version C of the form processing.

**Comment by smaaliki** [comment]
I implemented a couple of calculators that can be used in contact centers.

<https://github.com/smaaliki/p2>

**Comment by susanBuck** [comment]
Closing this post, but feel free to continue to share your projects if you haven't already.
