### ISSUE TITLE
Improving README.md files

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-spring2018#40]
As I've been reviewing Project 2 submissions, I've noticed students broadly listing sites like StackOverflow or W3 schools under their list of *Outside resources*. Without more specific links or context, this information is not meaningful.

If you end up on a site like StackOverflow or W3 schools and read some **information that you apply in your project**, take a second to just copy/paste that URL into your Readme file with a few words for context. Even if you feel the information is basic or common-knowledge, you can/should still cite it.

Of course the primary purpose of citing resources to to make sure any outside information is properly credited. Beyond that, though, **it serves as history of references applied to your work, which may come in handy for your future-self.**

I'm being generous in regards to point deductions for vague reference citations in P2 Readmes, but will be looking for better documentation moving forward in P3 and P4.

**Comment by ElijahMR** [comment]
Hello Ms. Buck,

With regards to the Php.net manual then would we have to include links to every page we use as reference? 

For example would this be how we are supposed to reference?

+ strtotime function reference via [strtotime](https://secure.php.net/manual/en/function.strtotime.php)
+ PHP float reference via [Floating point numbers](https://secure.php.net/manual/en/language.types.float.php)

Or would this be fine?

+ PHP strtotime and floating point numbers reference via [PHP Manual](https://secure.php.net/manual/en/)

**Comment by susanBuck** [comment]
Good question @ElijahMR - For references to manuals like php.net, w3 schools, laravel.com, etc, the latter is sufficient. 

For posts on forums like Stackoverflow, I'd link to the specific post.
