### ISSUE TITLE
Routes defaulting to 404 error page

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/dwa15-spring2018#43]
All,

I'm seeing a strange behavior with my routes not resolving, but instead defaulting to the HTTP 404 error page for Laravel. Following the instructions in the video (part 4) for this week, I create the following snippet in web.php:

```php 
Route::get('/books/{$title}', function ($title) {
    return 'You are viewing the book ' . $title;
});
```

When I go to http://foobooks.loc/books/war-and-peace in my brower, I get the "Sorry, the page you are looking for could not be found" error page.

What's confusing is looking at the output of "php artisan route:list" shows that the route is known:

| Domain | Method   | URI            | Name | Action  | Middleware   |
|:--------:|:----------:|:----------------|:------:|:---------:|:--------------:|
|        | GET HEAD | /              |      | Closure | web          |
|        | GET HEAD | api/user       |      | Closure | api,auth:api |
|        | GET HEAD | books/{$title} |      | Closure | web          |

Not sure what's going on. Looking at StackOverflow I see it's a issue that pops up, but my conf files are mapped correctly. Anyone else seeing this behavior?

**Comment by reelmatt** [comment]
Hi @gaderrick, it looks like the issue may be with the route in web.php. The variable in the path name should **not** have a `$`, just the curly braces, like so:

```php
Route::get('/books/{title}', function ($title) {
    return 'You are viewing the book ' . $title;
});
```

If I'm not mistaken, it's because the first part of the route method is Laravel syntax which seems to use `{ }` for defining variables, and the function call is PHP syntax, which uses `$` for variables.

**Comment by gaderrick** [comment]
@reelmatt Thanks... its been a long week :). On the plus side I thought I fat fingered something so I got to rework through recreated foobooks from a blank folder again.

**Comment by bwilks26** [comment]
Hi @gaderrick , I usually find the php artisan routs:list to be very helpful when debugging paths. I find it is also more helpful to actually go into the error files displayed on the screen and see what's going on that way, as there have been many times where the debugging error pages have helped me find minor bugs. Glad you resolved the issue!
