### ISSUE TITLE
Facades - Production Server  Class File Errors

### ISSUE THREAD

**Issue by oarangel** [susanBuck/dwa15-spring2018#46]
I completed the Facades exercise as described in lecture and can test the project locally with no issues. I then updated the composer.lock file, the git repository and production server files. But, I am not able to update  production server Class files, the following errors are displayed:

`In Application.php line 643:`

  `Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found`
 `Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found`

`Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1`

How can I load the Barryvdh Class files in the server?

**Comment by susanBuck** [comment]
Hi @oarangel  - Can you elaborate on what step is triggering those errors? 

I'm wondering if you're running `composer install` on production instead of `composer install --no-dev`. The former would cause problems because you're not specifying you only want packages in `require-dev`.

**Comment by oarangel** [comment]
I was running `composer install --no-dev` on production, issue was related to the **.env**  file. 
In the videos, it talks about the `production` setting but I  used the notes to setup my project and did not  change `APP_ENV`  to  `production`
Thank you @gaderrick and @susanBuck
