### ISSUE TITLE
Bonus material: Deployment script (UPDATED: WED MAR 21)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-spring2018#47]
I mentioned in Week 7's videos that I'd share some info on creating a deployment script to streamline the process of deploying code to production.

[Here are the notes for that...](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/deployment-script.md)

I tested on both Mac/Win, but let me know if you run into any issues on your end when implementing.

**Comment by amushal** [comment]
This is great.  I have added this to my p3.  Thanks.

**Comment by susanBuck** [comment]
## Update - Wed Mar 21
I just fixed a bug and added a new feature to the deploy script.

If you've already implemented this script in your project, I recommend replacing your existing `deploy.sh` script [with the updated version](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/deploy.sh).

__When replacing, be sure to modify the first two lines where you specify *your* doc root and server.__

### Bug fix
When choosing option 1, *Push and deploy any pending commits* it wasn't actually doing the push. 

[Fixed by adding `git push origin master` on line 36](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/deploy.sh#L35).

### New feature
In this week's (8) lecture videos, when discussing the nav bar I added to Foobooks, I point out how configs may be cached, requiring you to run `php artisan config:clear` in order to recognize new/changed configs.

This is a step we don't want to forget when deploying new code so it should be part of the deployment process. 

To accomplish this I made the deploy script look at the files that are changed as a result of running`git pull origin master` (on prod) and look for the keyword `config` in those file paths.

If it finds that keyword, it knows a config file was modified so it runs `php artisan config:clear` to refresh the config cache.

All this happens starting at [line 64](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/deploy.sh#L64).

**Comment by bwilks26** [comment]
Thank you! I have tried out the deploy script when testing out some features via development, and it is very helpful.
