### ISSUE TITLE
Array to string conversion issue with foobooks search example

### ISSUE THREAD

**Issue by brianyingling** [susanBuck/dwa15-spring2018#49]
Hello,

I'm working through the examples this week but I' m getting an error when trying to run the search function the BooksController. I get an ErrorException (E_NOTICE): Array to string conversion error and it refers to the return portion of the function. This is the code I'm using:

```php
public function search(Request $request) {
        $searchResults = [];
        $searchTerm = $request->input('searchTerm', null);
        if ($searchTerm) {
            $booksRawData = file_get_contents(database_path('/books.json'));
            $books = json_decode($booksRawData, true);
            foreach($books as $title => $book) {
                if ($request->has('caseSensitive')) {
                    $match = $title == $searchTerm;
                } else {
                    $match = strtolower($title) == strtolower($searchTerm);
                }
                if ($match) {
                    $searchResults[$title] = $book;
                }
            }
        }
        return view('books.search').with([
            'searchTerm'    => $searchTerm,
            'caseSensitive' => $request->has('caseSensitive'),
            'searchResults' => $searchResults
        ]);
    }
```

It's strange because I thought it was near-identical to what was discussed in lecture. Any ideas as to what I'm doing wrong? Thanks.

**Comment by brianyingling** [comment]
I figured it out.

`return view('books.search').with([`...

I should have been using this instead:

`return view('books.search')->with([`...

Silly arrow notation. :-/

**Comment by mcm223** [comment]
The arrow always gets me too! I'm so used to dot-notation coming from Swift.
