### ISSUE TITLE
solution: multiple id_rsa keys

### ISSUE THREAD

**Issue by charlie-harvard** [susanBuck/dwa15-spring2018#5]
If you've already had a **id_rsa** and **id_rsa.pub** key pair in your `~/.ssh` folder (for any reason, like me), then you may need to do a few things to make it work.

- Generate the RSA keys and save it with a different name.
- Use a config file to manage your RSA keys.

I came across [this article](https://coderwall.com/p/7smjkq/multiple-ssh-keys-for-different-accounts-on-github-or-gitlab) and found it's really helpful.

**Comment by susanBuck** [comment]
Great information - thanks for sharing!

**Comment by gaderrick** [comment]
Wow, I've been doing it the hard way all these years. Thanks for the info.

**Comment by amushal** [comment]
Very useful information, thank you.

**Comment by bwilks26** [comment]
Thanks for the tip Charlie!

**Comment by ElijahMR** [comment]
Hah, and I've been using switches like "-i" for ssh to choose which key pair to use. Thank you very much Charlie, this is an amazing quality of life improvement!

**Comment by balkasem** [comment]
useful information, thank you for sharing.
