### ISSUE TITLE
Issue when submitting the form data

### ISSUE THREAD

**Issue by mamdooh26** [susanBuck/dwa15-spring2018#50]
When I put /books/search' in form action as below, I got that the page is not found 
```html
<form method='GET' action='/books/search'>
```

but when I put the complete path as below, the search results shows correctly
```html
<form method='GET' action='/foobooks/public/books/search'>
```

How can make the first statement (action='/books/search') works properly as per the examples.

**Comment by smaaliki** [comment]
Mamdooh,  It seems that you forgot to show the example of the full path.

**Comment by mamdooh26** [comment]
Oh, thanks smaaliki
The full path is action='/foobooks/public/books/search'

**Comment by smaaliki** [comment]
Thanks. Your views should be in the /resources/views folder not in the public folder.

**Comment by susanBuck** [comment]
(*FYI @mamdooh26's original post was not showing the form tags because the code snippets were not formatted with proper Markdown. I've edited the original post to fix this problem.*)

@mamdooh26: Can you tell us more about the route(s) you've set up to handle the form submission to `/books/search`?

**Comment by mamdooh26** [comment]
@susanBuck 
routes are:
```html
Route::get('/books/search','BookController@search');

Route::get('/books/{title}', 'BookController@show');
```

**Comment by susanBuck** [comment]
Ok - looks good. Next question: can you tell us the exact URL you see in the browser when the form is submitted with the action set as follows:

```html
<form method='GET' action='/books/search'>
```

(Side note, we can help you troubleshoot this quicker if you update your repo on Github and share the URL with us so we can take a look at all the relevant code.)

**Comment by susanBuck** [comment]
Apologies for temporarily closing the issue; was an accidental button click.

**Comment by mamdooh26** [comment]
This URL is before performing the search:
```html
http://localhost:8080/foobooks/public/books/search
```
And this URL is after performing the search.
```html
http://localhost:8080/foobooks/public/books/search
```
http://localhost:8080/books/search?searchTerm=test

And this is the Github URL: https://github.com/mamdooh26/foobooks

**Comment by johnpura** [comment]
Could you share the VirtualHost block for the app on your local machine?

**Comment by mamdooh26** [comment]
@johnpura I didn't add a virtual host to this app.

**Comment by johnpura** [comment]
You'll need to add a VirtualHost block for your local XAMPP/MAMP server. Check out this link that explains how to do it...

https://github.com/susanBuck/dwa15-spring2018/blob/master/laravel/new-laravel-app.md

Also, check out this video from week 8 that goes over a security vulnerability. You'll want to implement that as well...

https://www.youtube.com/embed/t-ygiMlgHAI?rel=0&showinfo=0

Let us know if this fixes your issue...Good luck!

**Comment by archerdave** [comment]
As a note, if you're using the Pro version of MAMP, you do not need to input the VirtualHost block.  MAMP handles that for you.  It's still there.  The system still requires it, and it needs to be configured, but MAMP takes the settings you specify via the MAMP interface, and manages the VirtualHost blocks.

**Comment by mamdooh26** [comment]
Adding the VirtualHost fixes the issue. thanks @johnpura
