### ISSUE TITLE
Week 9 Assignment link leads to Week 8 Assignment

### ISSUE THREAD

**Issue by jaechong** [susanBuck/dwa15-spring2018#51]
From the **Week 9 page**, if you click on "Week 9 Assignment in Canvas...", it leads to **Week 8 assignment**.  Now I reopened Week 8 assignment with all the fields empty, when I reopened Week 7 assignment and left as, my grade ended up 0 although it was fixed later.
The proper link can be found from the **Assignments page on Canvas**.

**Comment by susanBuck** [comment]
Just corrected the link.
