### ISSUE TITLE
route not defined

### ISSUE THREAD

**Issue by amushal** [susanBuck/dwa15-spring2018#60]
I am having an issue to get the standard route syntax working as expected.
when I define my route as: ```Route::get('/contacts/search', 'ContactController@search');```, I get a **route not defined error**.

It seems I am not alone on this.  When I researched this issue, it was suggested to use the following syntax: ```Route::get('/contacts/search',['as' => 'contacts.search','uses' => 'ContactController@search']);``` which works for me, but I am still not sure why doing it the usual way is not working.

In my view/form the action is defined as ```{{ route('contacts.search') }}```

**Comment by gaderrick** [comment]
What is the output of the following command?

> php artisan route:list

**Comment by gaderrick** [comment]
Actually, I reread your initial post. In the first code you tried you don't have the route named (ie contacts.search). The second example that does work has it named. Try this and let us know if it fixes it:

`Route::get('contacts/search', 'ContactController@search')->name('contacts.search');`

**Comment by amushal** [comment]
btw, @gaderrick here is the route:list output for search route:
` GET|HEAD | contacts/search | App\Http\Controllers\ContactController@search | web,auth`

**Comment by johnpura** [comment]
Do you get the error when you use `action="/contacts/search"` in you form?

**Comment by amushal** [comment]
Interestingly enough, I don't.  So it must be related to using `{{ route('contacts.search') }}` that one must explicitly name the route with `->name('path').  It seems common practice to do so as I noticed when I did `php artisan make:auth` that was how the **login/logout/reset...** routes were called in my blade file.

**Comment by johnpura** [comment]
After a little research, I found out that the `route()` method is used in conjunction with Named Routes, which is why gaderrick's suggestion works. There is a `url()` helper method that I think would work without needing to define a named route...

`{{ url('contacts/search') }}`

Here is some info on Named Routes...

https://laravel.com/docs/5.6/routing#named-routes

**Comment by susanBuck** [comment]
👍 to @gaderrick for spotting the problem and @johnpura's supplemental explanation! 

I'll piggy-back on that with a little more background on the two different approaches:

## Approach 1 (what was shown in lecture/notes)
Don't name routes:
```php
Route::get('/hello/world', 'HelloController@world');
```

When linking to the routes, link to the actual path, like you would any other link:
```html
<a href='/hello/world'>Hello world</a>
```

Or, as @johnpura noted, you could use the `url()` helper method... 
```html
<a href='{{ url('/hello/world')'>Hello world</a>
```

Which will translate to a fully qualified URL (i.e. includes the http and domain):
```html
<a href='http://foobooks.loc/hello/world'>Hello world</a>
```

End result is effectively the same.

# Approach 2
Name routes when defining them:
```php
Route::get('/hello/world', 'HelloController@world')->name('helloWorld');
```

Then use the `route()` helper method when linking to it:
```html
<a href='{{ route('helloWorld') '>Hello world</a>
```

This would render as:
```html
<a href='http://foobooks.loc/hello/world'>Hello world</a>
```

**The benefit of naming routes is it gives you flexibility - you can later change the path to that route, and not have to find references to it in your views to update the path there as well.** 


Approach 2 is superior. The only reason I teach it with Approach 1 is it just keeps things more straight-forward when first introducing the concepts of routes.
