### ISSUE TITLE
XAMPP with MariaDB installed

### ISSUE THREAD

**Issue by johnpura** [susanBuck/dwa15-spring2018#61]
Hi, I noticed that my local XAMPP server is running MariaDB instead of MySQL. Will I need to install a version of XAMPP with MySQL or will MariaDB still work with the Laravel MySQL driver?

**Comment by susanBuck** [comment]
Nope, the version you have is fine. MariaDB is a fork of MySQL, and works the same for all our purposes. You will configure it just like a MySQL db (I used the same version of XAMPP you have when writing the notes).

If you're curious, here's some more info: [MariaDB vs MySQL: In-Depth Comparison](https://blog.panoply.io/a-comparative-vmariadb-vs-mysql)

**Comment by johnpura** [comment]
Phew!!...I really didn't want to do a re-install...Thanks!
