### ISSUE TITLE
Question on the Laravel setting for defaultStringLength

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/dwa15-spring2018#62]
I know in the class material we were told to set the defaultStringLength in Laravel to 191, but for P4 I need to be able to store a larger varchar for several fields. I did a little research, and want to make sure it is actually this easy:

1) Change the MySQL connection info to include this:
```
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',
```

instead of this:
```
'charset' => 'utf8mb4',
'collation' => 'utf8mb4_unicode_ci',
```
2) Update the following setting in the AppServiceProvider:
```
public function boot()
{
\Schema::defaultStringLength(191);
}
```
Is this the best way to store a larger string in MySQL? Or can I just increase the defaultStringLength in AppServiceProvider and increase the column size in MySQL?

**Comment by susanBuck** [comment]
If you change the charset/collation config (1) you don't need to specify the default string length (2).

Either one of these steps will address the issue, they just take a different approach to doing so:

1. Use a charset/collation that requires less space per character
2. Use less characters

**Comment by gaderrick** [comment]
Thanks
