### ISSUE TITLE
Production database setup - lecture video mistakenly omitted `--no-dev` when running `composer install`

### ISSUE THREAD

**Issue by johnpura** [susanBuck/dwa15-spring2018#63]
Hi,

Before running the seeders command to update the packages on our production server, should we use 

`composer install --no-dev` 

Instead of 

`composer install` 

The video in week 11 uses `composer install`, but I thought we use `composer install --no-dev` on production.

Thanks

**Comment by susanBuck** [comment]
You should use `composer install --no-dev`. 

Omitting `--no-dev` was an oversight on my part. I'll see if I can add a comment to the video to clarify that. Sorry for any confusion!

**Comment by susanBuck** [comment]
Update: Couldn't add an annotation on the video itself, but made a note on the Week 11 lecture outline, and also updated the notes to emphasize that `composer install --no-dev` needs to be run.

Thanks for the heads up @johnpura!

**Comment by johnpura** [comment]
Thank you!
