### ISSUE TITLE
Re-seed users' data

### ISSUE THREAD

**Issue by voggi** [susanBuck/dwa15-spring2018#71]
Hi all,

if you seed users into the database as outlined in the [notes](https://github.com/susanBuck/dwa15-spring2018/blob/master/laravel/auth-setup.md#seeds) a new hash is generated every time you run `php artisan db:seed`. Hence, an error will be thrown the second time you run this command, because Laravel will attempt to add a new user with a new password but an email that already exists.

You can move the `Hash::make('helloworld')` function into a second array argument. That way, the user will be retrieved on the basis of the name and email only while the password will be updated.

```php
use App\User;

# [...]

public function run()
{
    App\User::updateOrCreate(
        ['email' => 'jamal@harvard.edu', 'name' => 'Jamal Harvard'],
        ['password' => Hash::make('helloworld')]
    );
}
```

**Comment by susanBuck** [comment]
Good note. I always migrate fresh before seeding so never noticed it would fail when seeding twice.

**Comment by susanBuck** [comment]
FYI Updated the notes to follow your approach.
