### ISSUE TITLE
Problems factoring out controller code

### ISSUE THREAD

**Issue by reelmatt** [susanBuck/dwa15-spring2018#72]
I'm currently working on a search feature for my final project and seem to have it working as designed, but it is quite repetitive. Basically, I'm using the Laravel `filter()` [method on Collections](https://laravel.com/docs/5.6/collections#method-filter) to whittle down the potential results before displaying them to the user. The basic code/check is the same, so I thought I could factor it out à la [this bonus material note on streamlining controllers](https://github.com/susanBuck/dwa15-spring2018/issues/68).

When trying to implement that however, I kept running into data-type problems and attempting to display the results. Things were a Collection when I needed an array and vice-versa. Dumping the data at various points in the process showed that the types were changing in between the method calls (i.e. dumping before returning the results gave me what I was looking for, but back in the controller it was different).

Any ideas, or potentially different ways for implementing a search feature? I've included relevant code snippets below.

**Current working methods in my `ApartmentController.php`** -- but repeats similar code (there's about 8 different blocks based on an individual search criterion)
```php
if($this->price != null) {
    $results = $results->filter(function($value) {
        if($value->price < $this->price) {
            #dump('match price');
            return $value;
        }
        return 0;
    });
}

if($this->beds != null) {
   $results = $results->filter(function($value) {
        if($value->beds > $this->beds) {
            dump('match beds');
            return $value;
        }
        return 0;
    });
}
```

**Attempted factoring out of code based on class example [from here](https://github.com/susanBuck/dwa15-spring2018/issues/68)**
```php
<?php

namespace App\Actions\Listing;

use App\Listing;

class SearchListings
{
    public function __construct($listings, $parameter, $element)
    {
        $this->parameter = $parameter;
        $this->element = $element;
        if ($parameter != null) {
            $listings = $listings->filter(function ($value) {
                #dump($value->price);
                #dump($this->foobar);
                $element = $this->element;
                if ($value->$element < $this->parameter) {
                    #dump('match price');
                    return $value;
                }

                return 0;
            });
        }
        dump('results within SearchListings');
        dump($listings);
        $this->listings = $listings;
        return $listings;
}
```

**Incorporating above attempt into my `ApartmentController.php` file**
```php
$listings = Listing::all();
$results = new SearchListings($listings, $this->price, 'price');
return view('apartments.results')->with([
            'results' => $results,
]);
```

**Comment by susanBuck** [comment]
In the code above, you're attempting to return a value (`$listings`) from the __construct method, but constructors can't return values, they return an instance of the class they're constructing.

Instead, to get data "out" of the action class, you set it as a class property and then you can access it from the object.

In your case, you've already got this partially set up because you have `$this->listings = $listings` in your construct method.

Then, in your controller, we see that `$results` holds a SearchListings object... thus, we should be able to get the listing data via `$results->listings`.


Example:
```php
$results = new SearchListings($listings, $this->price, 'price');
return view('apartments.results')->with([
            'results' => $results->listings, # <-----
]);
```

Note this is similar to the pattern I showed in the streamlining controller's videos. I created a class property called `vda` which I then accessed in the controller:

```php
$action = new ShowIndex($request->user)
return view('books.index')->with($action-vda);
````

**Comment by reelmatt** [comment]
Thanks @susanBuck, this framing helps me a lot to wrap my head around the problem!

In case fellow students find this helpful, I ended up structuring my `SearchListings.php` class as follows:

```php
<?php

namespace App\Actions\Listing;

use App\Listing;

class SearchListings
{
    public function __construct($listings, $queries)
    {
        $this->listings = $listings;
        $this->queries = $this->filterQuery($queries);
        $this->listings = $this->search();
    }
    public function filterQuery($queries) 
    {
        /*logic goes here*/
    }

    public function formatQueries()
    {
        /*logic goes here*/
    }

    public function search()
    {
        /*logic goes here*/
    }
}
```
and then as demonstrated above, access the data using statements akin to
```php
'results' => $results->listings
```
