### ISSUE TITLE
Seeder does not exist error on production

### ISSUE THREAD

**Issue by anup24** [susanBuck/dwa15-spring2018#73]
I am getting below error on production for Users seeder. This works properly on local setup. I also checked the content of the file on the server, latest code is on the server.

`Seeding: UsersTableSeeder
In Container.php line 767:
Class UsersTableSeeder does not exist`

Commands that I use after taking latest code:
1) `php artisan migrate:fresh`
2) `php artisan db:seed`

**Comment by susanBuck** [comment]
After deploying new code on production, you should run `composer update`. This will not only check for any package updates, but it will regenerate your autoloading classmap to recognize new class files (including seeders). 

Alternatively, you could run `composer dump-autoload` to just regenerate the classmap.

ref: <https://github.com/susanBuck/dwa15-spring2018/blob/master/laravel/db-production.md#error-class-bookstableseeder-does-not-exist>

**Comment by anup24** [comment]
`composer update` worked for me. Thanks.
