### ISSUE TITLE
Supplemental Material, Increasing server security

### ISSUE THREAD

**Issue by mildredfakoya** [susanBuck/dwa15-spring2018#8]
I noticed something while playing around with the server security, the supplemental material gave the procedure for creating a new user and adding the user to the admin group. Is the admin group the same as the sudo group? In the past I have added the new user in a slightly different way and disabled the root user, then run every command using sudo before the command, is my procedure correct? Is there a security risk to what i am doing? below is the command i have used previously:
`add user username`  
`usermod -aG sudo username`  
`mkdir /home/username/ .ssh `
`chmod 0700 /home/username/ .ssh`    
`cp -Rfv /root/ .ssh /home/username/ `   
`chown -Rfv username.username /home/username/ .ssh`   
`chown -R username:username /home/username/ ` 
`gpassword -a username sudo`  
`echo "username ALL=(ALL) NOPASSWD: ALL" | (EDITOR = "tee -a" visudo ` 
`service ssh restart `
`usermod -s /bin/bash username `

**Comment by susanBuck** [comment]
(FYI: For others reading this, these are the notes Mildred is referring to: [Increasing server security](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/increasing-server-security.md))

In the procedures described in the notes, the new user is not added to the admin group. A new user is created with their own new group. 

That user is then given access to run commands as any user and as any group:

```
susanbuck ALL=(ALL:ALL) ALL
```

It looks like the difference in your procedure is you're granting the new user `ALL` access vs `ALL:ALL` access.

For the difference between the two, [check out this post](https://askubuntu.com/a/43344).

**Comment by mildredfakoya** [comment]
Thanks.
