### ISSUE TITLE
Video repeats a section

### ISSUE THREAD

**Issue by archerdave** [susanBuck/dwa15-spring2018#9]
It looks like the [Week 2 part 5 video](https://www.youtube.com/embed/hniIKbnX8HU?rel=0&showinfo=0) repeats a section of content.  The section that starts at 11:43 runs again at 15:24.

**Comment by JoelTurnblade** [comment]
I didn't notice until you pointed it out.

**Comment by susanBuck** [comment]
Thanks for the heads up. I'll re-upload a fixed version after I finish publishing today's videos.

**Comment by susanBuck** [comment]
Re-uploaded corrected version. 
I'll pretend I made that mistake in honor of Groundhog day last week. : )
